import turtle

pen=turtle.Turtle()
pen.speed(5)
pen.color('blue')
pen.forward(200)
pen.left(120)
pen.forward(200)
pen.left(120)
pen.fillcolor("blue")
pen.begin_fill()
pen.home()

pen.color('red')
pen.left(180)
pen.forward(200)
pen.right(120)
pen.forward(200)
pen.home()
pen.color("white")
pen.penup()
pen.goto(-100, 0)
pen.pendown()
pen.left(60)
pen.forward(100)
pen.color("black")
pen.forward(100)
pen.right(120)
pen.forward(100)
pen.color("white")
pen.forward(100)
pen.end_fill()

pen.fillcolor("blue")
pen.begin_fill()
pen.pensize(3)
pen.pencolor("red")
pen.forward(100)
pen.left(120)
pen.forward(100)
pen.left(120)
pen.home()
pen.end_fill()

turtle.done()
